In [2]:
import pandas as pd

In [5]:
# read file
lou_inspection = pd.read_excel("louisville_inspection.xlsx")
lou_inspection

,EstablishmentID,InspectionID,Ins_TypeDesc,EstablishmentName,PlaceName,Address,Address2,City,State,Zip,TypeDescription,InspectionDate,score,Grade,NameSearch,Intersection,ObjectId
0,29956,1684470,REGULAR,CVS #6211,NaN,3721 LEXINGTON RD,NaN,LOUISVILLE,KY,40207,PRE-PACKAGED RETAIL,2022/07/06 00:00:00,100,NaN,CVS #6211,NaN,1
1,29967,1699737,REGULAR,NEIGHBORHOOD FOOD MART,NaN,542 LAMPTON ST,NaN,LOUISVILLE,KY,40203,SUPERMARKET WITH PROCESSING,2022/09/07 00:00:00,97,NaN,NEIGHBORHOOD FOOD MART,NaN,2
2,29979,1698679,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,NaN,3
3,29979,1698680,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,98,NaN,CIRCLE K #4700075,NaN,4
4,29979,1731827,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11225,118688,1758428,OTHER,GRINGOS FOOD TRUCKS,NaN,NaN,NaN,LOUISVILLE,KY,40202,SELF-CONTAINED MOBILE FOOD UNITS,2023/05/25 00:00:00,100,NaN,GRINGOS FOOD TRUCKS,NaN,11226
11226,118697,1758467,OTHER,FRICKLED PICKLE EXPRESS,NaN,NaN,NaN,LOUISVILLE,KY,40202,SELF-CONTAINED MOBILE FOOD UNITS,2023/05/25 00:00:00,98,NaN,FRICKLED PICKLE EXPRESS,NaN,11227
11227,118710,1758790,OTHER,TIENDA LATINOAMERICANO #3,NaN,8040 NEW LAGRANGE RD,NaN,LOUISVILLE,KY,40222,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/05/04 00:00:00,98,NaN,TIENDA LATINOAMERICANO #3,NaN,11228
11228,118710,1758791,OTHER,TIENDA LATINOAMERICANO #3,NaN,8040 NEW LAGRANGE RD,NaN,LOUISVILLE,KY,40222,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/05/04 00:00:00,96,NaN,TIENDA LATINOAMERICANO #3,NaN,11229
11229,118711,1758835,OTHER,TRIO SPORTS BAR AND GRILL,NaN,4900 PRESTON HWY,NaN,LOUISVILLE,KY,40213,FOOD SERVICE,2023/05/01 00:00:00,99,NaN,TRIO SPORTS BAR AND GRILL,NaN,11230

In [7]:
# Change all headers to lower case letters
lou_inspection.columns = lou_inspection.columns.str.lower()
lou_inspection

,establishmentid,inspectionid,ins_typedesc,establishmentname,placename,address,address2,city,state,zip,typedescription,inspectiondate,score,grade,namesearch,intersection,objectid
0,29956,1684470,REGULAR,CVS #6211,NaN,3721 LEXINGTON RD,NaN,LOUISVILLE,KY,40207,PRE-PACKAGED RETAIL,2022/07/06 00:00:00,100,NaN,CVS #6211,NaN,1
1,29967,1699737,REGULAR,NEIGHBORHOOD FOOD MART,NaN,542 LAMPTON ST,NaN,LOUISVILLE,KY,40203,SUPERMARKET WITH PROCESSING,2022/09/07 00:00:00,97,NaN,NEIGHBORHOOD FOOD MART,NaN,2
2,29979,1698679,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,97,A,CIRCLE K #4700075,NaN,3
3,29979,1698680,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2022/09/01 00:00:00,98,NaN,CIRCLE K #4700075,NaN,4
4,29979,1731827,REGULAR,CIRCLE K #4700075,NaN,1630 ARTHUR ST,NaN,LOUISVILLE,KY,40208,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/01/27 00:00:00,95,A,CIRCLE K #4700075,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11225,118688,1758428,OTHER,GRINGOS FOOD TRUCKS,NaN,NaN,NaN,LOUISVILLE,KY,40202,SELF-CONTAINED MOBILE FOOD UNITS,2023/05/25 00:00:00,100,NaN,GRINGOS FOOD TRUCKS,NaN,11226
11226,118697,1758467,OTHER,FRICKLED PICKLE EXPRESS,NaN,NaN,NaN,LOUISVILLE,KY,40202,SELF-CONTAINED MOBILE FOOD UNITS,2023/05/25 00:00:00,98,NaN,FRICKLED PICKLE EXPRESS,NaN,11227
11227,118710,1758790,OTHER,TIENDA LATINOAMERICANO #3,NaN,8040 NEW LAGRANGE RD,NaN,LOUISVILLE,KY,40222,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/05/04 00:00:00,98,NaN,TIENDA LATINOAMERICANO #3,NaN,11228
11228,118710,1758791,OTHER,TIENDA LATINOAMERICANO #3,NaN,8040 NEW LAGRANGE RD,NaN,LOUISVILLE,KY,40222,"RETAIL-FOOD 10,000 SQ FT OR LESS",2023/05/04 00:00:00,96,NaN,TIENDA LATINOAMERICANO #3,NaN,11229
11229,118711,1758835,OTHER,TRIO SPORTS BAR AND GRILL,NaN,4900 PRESTON HWY,NaN,LOUISVILLE,KY,40213,FOOD SERVICE,2023/05/01 00:00:00,99,NaN,TRIO SPORTS BAR AND GRILL,NaN,11230

In [8]:
# Force all string values to be lowercase
lou_inspection = lou_inspection.applymap(lambda x: x.lower() if type(x) == str else x)
lou_inspection

,establishmentid,inspectionid,ins_typedesc,establishmentname,placename,address,address2,city,state,zip,typedescription,inspectiondate,score,grade,namesearch,intersection,objectid
0,29956,1684470,regular,cvs #6211,NaN,3721 lexington rd,NaN,louisville,ky,40207,pre-packaged retail,2022/07/06 00:00:00,100,NaN,cvs #6211,NaN,1
1,29967,1699737,regular,neighborhood food mart,NaN,542 lampton st,NaN,louisville,ky,40203,supermarket with processing,2022/09/07 00:00:00,97,NaN,neighborhood food mart,NaN,2
2,29979,1698679,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2022/09/01 00:00:00,97,a,circle k #4700075,NaN,3
3,29979,1698680,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2022/09/01 00:00:00,98,NaN,circle k #4700075,NaN,4
4,29979,1731827,regular,circle k #4700075,NaN,1630 arthur st,NaN,louisville,ky,40208,"retail-food 10,000 sq ft or less",2023/01/27 00:00:00,95,a,circle k #4700075,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11225,118688,1758428,other,gringos food trucks,NaN,NaN,NaN,louisville,ky,40202,self-contained mobile food units,2023/05/25 00:00:00,100,NaN,gringos food trucks,NaN,11226
11226,118697,1758467,other,frickled pickle express,NaN,NaN,NaN,louisville,ky,40202,self-contained mobile food units,2023/05/25 00:00:00,98,NaN,frickled pickle express,NaN,11227
11227,118710,1758790,other,tienda latinoamericano #3,NaN,8040 new lagrange rd,NaN,louisville,ky,40222,"retail-food 10,000 sq ft or less",2023/05/04 00:00:00,98,NaN,tienda latinoamericano #3,NaN,11228
11228,118710,1758791,other,tienda latinoamericano #3,NaN,8040 new lagrange rd,NaN,louisville,ky,40222,"retail-food 10,000 sq ft or less",2023/05/04 00:00:00,96,NaN,tienda latinoamericano #3,NaN,11229
11229,118711,1758835,other,trio sports bar and grill,NaN,4900 preston hwy,NaN,louisville,ky,40213,food service,2023/05/01 00:00:00,99,NaN,trio sports bar and grill,NaN,11230